# Generated by Django 6.0.2 on 2026-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '총관리자'), ('manager', '책임자'), ('agency', '대행사'), ('seller', '셀러')], default='seller', max_length=10, verbose_name='역할'),
        ),
    ]
