# Generated by Django 6.0.2 on 2026-02-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '총관리자'), ('accountant', '경리'), ('manager', '책임자'), ('agency', '대행사'), ('seller', '셀러')], default='seller', max_length=12, verbose_name='역할'),
        ),
    ]
