# Generated by Django 6.0.2 on 2026-02-15 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='상품코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='기본 단가')),
                ('schema', models.JSONField(default=list, help_text='주문 시 입력할 필드 정의 [{"name":"url","label":"URL","type":"text","required":true}, ...]', verbose_name='입력 스키마')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='적용 단가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to=settings.AUTH_USER_MODEL, verbose_name='적용 대상')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_policies', to='products.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '단가 정책',
                'verbose_name_plural': '단가 정책',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
