# Generated by Django 6.0.2 on 2026-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_deadline_days',
            field=models.PositiveIntegerField(default=30, help_text='주문 시 자동 설정되는 마감일까지의 일수', verbose_name='기본 마감일(일)'),
        ),
    ]
