# Generated by Django 6.0.2 on 2026-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_default_deadline_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_work_days',
            field=models.PositiveIntegerField(default=30, verbose_name='최대 작업일 수'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_work_days',
            field=models.PositiveIntegerField(default=1, verbose_name='최소 작업일 수'),
        ),
    ]
