# Generated by Django 6.0.2 on 2026-02-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_max_work_days_product_min_work_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_deadline_days',
        ),
    ]
