# Generated by Django 6.0.2 on 2026-02-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_default_deadline_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='원가 (총 관리자 단가)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='업체별 개별 단가가 없을 때 대행사/셀러에게 적용되는 기본 단가', max_digits=10, verbose_name='기본 단가 (대행사 기본 적용 단가)'),
        ),
    ]
