# Generated by Django 6.0.2 on 2026-02-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cost_price_alter_product_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
