# Generated by Django 6.0.2 on 2026-02-15 10:06

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories = [
        {'name': '플레이스 리워드', 'icon': 'bi-geo-alt', 'display_order': 1},
        {'name': '플레이스 배포', 'icon': 'bi-shop', 'display_order': 2},
        {'name': '네이버 쇼핑', 'icon': 'bi-bag', 'display_order': 3},
        {'name': '쿠팡', 'icon': 'bi-cart', 'display_order': 4},
        {'name': '인스타그램', 'icon': 'bi-instagram', 'display_order': 5},
    ]
    for cat in categories:
        Category.objects.get_or_create(name=cat['name'], defaults=cat)


def reverse_seed(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(
        name__in=['플레이스 리워드', '플레이스 배포', '네이버 쇼핑', '쿠팡', '인스타그램']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_product_category'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
