# Generated by Django 6.0.2 on 2026-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reduction_rate',
            field=models.PositiveIntegerField(default=0, help_text='총 타수에서 실제 투입하지 않는 비율 (예: 30 = 30% 감음)', verbose_name='감은 비율 (%)'),
        ),
    ]
