# Generated by Django 6.0.2 on 2026-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_reduction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepolicy',
            name='reduction_rate',
            field=models.PositiveIntegerField(blank=True, help_text='null이면 상품 기본 감은 비율 사용', null=True, verbose_name='감은 비율 (%)'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='적용 단가'),
        ),
    ]
