"""QCA accounts → Unified Platform PostgreSQL migration.

Decrypts passwords with QCA key, re-encrypts with unified platform key,
inserts 13 accounts with company_id and unit costs.

Usage: python scripts/migrate-qca-accounts.py
  (run from api-server container on EC2, or locally with dependencies)
"""

import base64
import hashlib
import json
import sys

from cryptography.fernet import Fernet

# ============================================================
# QCA encryption (PBKDF2-SHA256 + salt)
# ============================================================
QCA_SECRET_KEY = "jtwolab1234"

def qca_derive_key(secret: str) -> bytes:
    dk = hashlib.pbkdf2_hmac(
        "sha256",
        secret.encode("utf-8"),
        b"quantum-campaign-salt",
        iterations=100_000,
    )
    return base64.urlsafe_b64encode(dk)

def qca_decrypt(encrypted: str) -> str:
    key = qca_derive_key(QCA_SECRET_KEY)
    f = Fernet(key)
    return f.decrypt(encrypted.encode("utf-8")).decode("utf-8")

# ============================================================
# Unified Platform encryption (SHA-256)
# ============================================================
UNIFIED_SECRET_KEY = "j2lab-platform-secret-key-change-me-in-production-2026"

def unified_encrypt(plain: str) -> str:
    key_bytes = hashlib.sha256(UNIFIED_SECRET_KEY.encode()).digest()
    fernet_key = base64.urlsafe_b64encode(key_bytes)
    f = Fernet(fernet_key)
    return f.encrypt(plain.encode("utf-8")).decode("utf-8")

# ============================================================
# Account data (from QCA SQLite)
# ============================================================
# company_id: 제이투랩=2, 일류기획=6
ACCOUNTS = [
    {"qca_id": 1,  "user_id": "트래픽 제이투랩",     "company_id": 2, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 2,  "user_id": "월보장 제이투랩",     "company_id": 2, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 3,  "user_id": "월보장 일류기획",     "company_id": 6, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 4,  "user_id": "월보장 일류기획24",   "company_id": 6, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 5,  "user_id": "트래픽 일류기획",     "company_id": 6, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 6,  "user_id": "트래픽 제이투랩24",   "company_id": 2, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 7,  "user_id": "월보장 제이투랩24",   "company_id": 2, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 8,  "user_id": "트래픽 일류기획24",   "company_id": 6, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 9,  "user_id": "저장 일류기획",       "company_id": 6, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 10, "user_id": "류 리워드 저장",      "company_id": 6, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 11, "user_id": "관리형 일류기획",     "company_id": 6, "unit_cost_traffic": 21, "unit_cost_save": 31},
    {"qca_id": 12, "user_id": "저장 일류기획24",     "company_id": 6, "unit_cost_traffic": 25, "unit_cost_save": 35},
    {"qca_id": 13, "user_id": "저장 제이투랩",       "company_id": 2, "unit_cost_traffic": 21, "unit_cost_save": 31},
]

# QCA encrypted passwords (from SQLite)
QCA_PASSWORDS = {
    1:  "gAAAAABpgu73VAG_F6UlYF-bvcZmIism0XakHIkOks9JwJ6y8-lzlBoRgXYplx4QxI-m89MIt6xUvXU3_AY8NDCMCv_BDuGBPw==",
    2:  "gAAAAABpgxIleMWxkTVWQLL2p65I8jYRZ6gKeihUc0rhjgDUKOBVwuS3mvD1zJJ7dBICzQgjpf7Ou6QYvXC36tf602Utr6Gt-Q==",
    3:  "gAAAAABpgxoi5tQV5kDtWKGeVkCaEjD731duJFjQTz3eBSUdRMGSz10tVKU84ivH0TF0KPr9EncB4VCIl3ISOXbKJkVCWGzwEQ==",
    4:  "gAAAAABpgxoze1fiYkWYk1uc32xfaMdMlcBt3PJxjd3NrxIzJUvycYgqbJ7w0dOgMDWYsJmrnLwOSe5UcOKW5k17E6LiVflbhg==",
    5:  "gAAAAABpg1zpLeSaOWXe1YXGy93yWHQG2sovvyj5wcmwRcrZBRmshTR4jO50AhO8g0hzzJyttz7VLIBEoXzS_BJTAJb0kpL2Iw==",
    6:  "gAAAAABphFgdPc56mK_o7Xh9q3V5-wbKfQSYJ5iYcYuPnOUnUmCKeQtCRbF-aLEdeHQ2x9_Uf24Qy_yaD4uVzCqEwXrsPTz0hQ==",
    7:  "gAAAAABphdvpSbbaxfyK4Df8jnOiWKnRfv7zjPOKyg43r-Yx8i7MDllT_1ShuKmT-C4WiO-mzrhrI2lPtYLcBX5aA1dmUiupow==",
    8:  "gAAAAABpje_p41jpXAxb34ng7XDOHOrA2BL5VAAafdGrJXCRFtRxhWIVs_ji2gs9D00QY0wpsU8MCiCmIHnvHILLCaQ1GqYTyQ==",
    9:  "gAAAAABpjhdD_nx7fcsO8WL6xhDAaetyn8JFP3BNbHb2MGLlCZT8fsppb6F3rRLHKLGG6Qx0-VVGXXlg4X8Xx48VZmL2NQVYPQ==",
    10: "gAAAAABpjz4MoWxy3ngtMADcFyaeqViJgEjk5Eba2j6HsNMGRi7kzXIgsDPI9tgi93y2awP9pnci5aYBqEn7WwjQresS_JVrJg==",
    11: "gAAAAABpj0UoEa0m_Kw80t6ZVPyWjk-SGqLZCrSynrLc5K4jgL2eMhKGNvp8HIDJV7CeCeDUNBJudVtcqIsAermBwBMsRRsdaQ==",
    12: "gAAAAABplwWmppvaZanHCYOIcZz6gNZ-hMyAiSs8hZ9f-Kl4iKMeRdupZUwxq221hV7NCNoOXlXr_fmMHvsaBzhFZ-nl3p1hVQ==",
    13: "gAAAAABpmCMRHdflvdOQVbANopJcbpJ9N6iZCbbLPqhkbFhZ8p6iLwodhugYfeen-x0L0SQIun_FmZApMO7HooI3ufMa4sj1ZQ==",
}


def generate_sql():
    """Generate SQL INSERT statements with re-encrypted passwords."""
    print("-- QCA Accounts Migration")
    print("-- Generated by migrate-qca-accounts.py")
    print()

    for acc in ACCOUNTS:
        qca_id = acc["qca_id"]
        user_id = acc["user_id"]
        encrypted_pw = QCA_PASSWORDS[qca_id]

        # Decrypt with QCA key
        try:
            plain_pw = qca_decrypt(encrypted_pw)
        except Exception as e:
            print(f"-- ERROR: Failed to decrypt account {qca_id} ({user_id}): {e}")
            continue

        # Re-encrypt with unified platform key
        new_encrypted = unified_encrypt(plain_pw)

        # Escape single quotes in strings
        user_id_escaped = user_id.replace("'", "''")
        new_encrypted_escaped = new_encrypted.replace("'", "''")

        sql = (
            f"INSERT INTO superap_accounts "
            f"(user_id_superap, password_encrypted, company_id, "
            f"unit_cost_traffic, unit_cost_save, assignment_order, is_active) "
            f"VALUES ("
            f"'{user_id_escaped}', "
            f"'{new_encrypted_escaped}', "
            f"{acc['company_id']}, "
            f"{acc['unit_cost_traffic']}, "
            f"{acc['unit_cost_save']}, "
            f"{qca_id}, "  # assignment_order = original QCA id order
            f"true"
            f") ON CONFLICT (user_id_superap) DO NOTHING;"
        )
        print(sql)
        print(f"-- OK: {user_id} (password decrypted & re-encrypted)")

    print()
    print("-- Done. Total: 13 accounts")


def write_sql_file(filepath: str):
    """Write SQL to file with proper UTF-8 encoding."""
    lines = []
    lines.append("-- QCA Accounts Migration")
    lines.append("-- Generated by migrate-qca-accounts.py\n")

    for acc in ACCOUNTS:
        qca_id = acc["qca_id"]
        user_id = acc["user_id"]
        encrypted_pw = QCA_PASSWORDS[qca_id]

        try:
            plain_pw = qca_decrypt(encrypted_pw)
        except Exception as e:
            lines.append(f"-- ERROR: Failed to decrypt account {qca_id} ({user_id}): {e}")
            continue

        new_encrypted = unified_encrypt(plain_pw)

        user_id_escaped = user_id.replace("'", "''")
        new_encrypted_escaped = new_encrypted.replace("'", "''")

        sql = (
            f"INSERT INTO superap_accounts "
            f"(user_id_superap, password_encrypted, company_id, "
            f"unit_cost_traffic, unit_cost_save, assignment_order, is_active) "
            f"VALUES ("
            f"'{user_id_escaped}', "
            f"'{new_encrypted_escaped}', "
            f"{acc['company_id']}, "
            f"{acc['unit_cost_traffic']}, "
            f"{acc['unit_cost_save']}, "
            f"{qca_id}, "
            f"true"
            f") ON CONFLICT (user_id_superap) DO NOTHING;"
        )
        lines.append(sql)
        lines.append(f"-- OK: {user_id}")

    lines.append("\n-- Done. Total: 13 accounts")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"SQL written to: {filepath}")


if __name__ == "__main__":
    # Test decryption
    try:
        test_pw = qca_decrypt(QCA_PASSWORDS[1])
        print(f"Account 1 decrypt OK (length: {len(test_pw)})")
    except Exception as e:
        print(f"DECRYPT FAILED: {e}")
        sys.exit(1)

    # Write SQL file
    output_path = "scripts/qca-accounts.sql"
    write_sql_file(output_path)
