# Generated by Django 6.0.2 on 2026-02-15 06:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=15, verbose_name='상태')),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='총 금액')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='건수')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', '충전'), ('withdraw', '차감'), ('refund', '환불')], max_length=10, verbose_name='거래 유형')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='거래 후 잔액')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order', verbose_name='관련 주문')),
            ],
            options={
                'verbose_name': '잔액 거래',
                'verbose_name_plural': '잔액 거래',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='행 번호')),
                ('data', models.JSONField(default=dict, verbose_name='입력 데이터')),
                ('unit_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='단가')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=15, verbose_name='상태')),
                ('result_message', models.TextField(blank=True, verbose_name='처리 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 항목',
                'verbose_name_plural': '주문 항목',
                'ordering': ['row_number'],
            },
        ),
    ]
