# Generated by Django 6.0.2 on 2026-02-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, help_text='리워드 상품 만료 날짜', null=True, verbose_name='마감일'),
        ),
    ]
