# Generated by Django 6.0.2 on 2026-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_confirmed_at_order_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='총 수량'),
        ),
    ]
