# Generated by Django 6.0.2 on 2026-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_approved_at_order_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', '접수완료'), ('processing', '작업중'), ('completed', '완료'), ('cancelled', '취소')], default='submitted', max_length=15, verbose_name='상태'),
        ),
    ]
